CREATE TABLE `beldtp`.`answer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `label` varchar(255) DEFAULT NULL,
  `language` int DEFAULT NULL,
  `text` longtext,
  `type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('registration','This bot','This bot','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('language','Language','Language','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('languageSuccess','You pick English','You pick English','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('main','Main menu','Main menu','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('back','Back','Back','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('setting','Setting','Setting menu','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('help','Help ','Help ','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('configuration','Configuration','Configuration','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('add','Add','Add','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addLocation','Location','Location','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addPhotoCount','Photo count','Photo count : ','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addVideoCount','Video count','Video count : ','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirm','Confirm Incident','Confirm Incident','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameter','Requires photo or video, description and location.','Requires photo or video, description and location.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmBuild','Your request has been sent','Your request has been sent','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTime','When this is happen?','When this is happen?','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTimeNow','Now','Now','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTimeSelect','Select','Select','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeDay','Please pick the day.','Please pick the day.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeHour','Please pick the hour.','Please pick the hour.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeMinute','Please pick the minute.','Please pick the minute.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeMonth','Please pick the month.','Please pick the month.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('january','January','January','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('february','February','February','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('march','March','March','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('april','April','April','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('may','May','May','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('june','June','June','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('july','July','July','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('august','August','August','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('september','September','September','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('october','October','October','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('november','November','November','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('december','December','December','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeYear','Please pick the year','Please pick the year.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('monday','Monday','Monday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('tuesday','Tuesday','Tuesday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('wednesday','Wednesday','Wednesday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('thursday','Thursday','Thursday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('friday','Friday','Friday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('saturday','Saturday','Saturday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('sunday','Sunday','Sunday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('verifyBuild','Verify','Verify','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('rejectIncident','Reject incident','Reject incident','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queue','Queue','Queue','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queueBuildSize','Build incident size','Build incident size','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queueRejectSize','Reject incident size','Reject incident size','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('editBuild','Edit incident','Edit incident','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('buildIncident','Build incident','Build incident','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('rejectBuild','Reject incident','Reject incident','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('deleteIncident','Delete incident','Delete incident','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('exception','This is bad request. Try again.','This is bad request. Try again.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('statistics','statistics','statistics','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('about','About the bot','About bot information','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('profile','Profile','Profile Information','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeToday','Today','Today','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeYesterday','Yesterday','Yesterday','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('privateStatistics','privateStatistics','privateStatistics','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('publicStatistics','publicStatistics','publicStatistics','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterLocation','Requires photo or video, description and location.','Requires photo or video, description and location.','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterMedia','Requires photo or video','Requires photo or video','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterText','Requires description','Requires description','2');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('registration','Гэты бот','Гэты бот','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('language','Мова','Мова','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('languageSuccess','Вы выбралі беларускую мову.','Вы выбралі беларускую мову.','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('main','Галоўная','Галоўная','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('back','Назад','Назад','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('setting','Налады','Налады 
бла-бла','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('help','Дапамога','Дапамога 
бла-бла','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('configuration','Канфігурацыя','Канфігурацыя','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('add','Дадаць','Дадаць бла-бла','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addLocation','Месцазнаходжанне','Месцазнаходжанне','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addPhotoCount','Колькасць фотаздымкаў','Колькасць фотаздымкаў : ','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addVideoCount','Колькасць відэа','Колькасць відэа : ','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirm','Пацвердзіць','Пацвердзіць','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameter','Патрабуецца фота ці відэа, апісанне і месцазнаходжанне.','Патрабуецца фота ці відэа, апісанне і месцазнаходжанне.','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmBuild','Ваша заяўка адпраўлена','Ваша заяўка адпраўлена','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTime','Калі гэта адбылося ?','Калі гэта адбылося ?','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTimeNow','Зараз','Зараз','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTimeSelect','Выбраць іншы час','Выбраць іншы час','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeDay','Выберыце дзень месяца','Выберыце дзень месяца','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeHour','Выберыце гадзіну','Выберыце гадзіну','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeMinute','Выберыце дакладны час','Выберыце дакладны час','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeMonth','Выберыце месяц','Выберыце месяц','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('january','Студзень','Студзень','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('february','Люты','Люты','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('march','Сакавiк','Сакавiк','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('april','Красавiк','Красавiк','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('may','Май','Май','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('june','Червень','Червень','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('july','Лiпень','Лiпень','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('august','Жнiвень','Жнiвень','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('september','Верасень','Верасень','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('october','Кастрычнiк','Кастрычнiк','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('november','Лiстапад','Лiстапад','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('december','Снежань','Снежань','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeYear','Выберыце год','Выберыце год','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('monday','Панядзелак','Панядзелак','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('tuesday','Аўторак','Аўторак','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('wednesday','Серада','Серада','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('thursday','Чацвер','Чацвер','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('friday','Пятніца','Пятніца','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('saturday','Субота','Субота','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('sunday','Нядзеля','Нядзеля','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('verifyBuild','Пацвердзіць','Пацвердзіць','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('rejectIncident','Адхіленыя здарэння','Адхіленыя здарэння','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queue','Чарга','Чарга','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queueBuildSize','Колькасць адпраўленых здарэнняў ','Колькасць адпраўленых здарэнняў : ','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queueRejectSize','Колькасць адхіленых здарэнняў','Колькасць адхіленых здарэнняў : ','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('editBuild','Рэдагаваць','Рэдагаваць','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('buildIncident','Адпраўленыя здарэння','Адпраўленыя здарэння','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('rejectBuild','Адхіленыя здарэння','Адхіленыя здарэння','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('deleteIncident','Выдаленыя здарэння','Выдаленыя здарэння','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('exception','This is bad request. Try again.','This is bad request. Try again.','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('statistics','statistics','statistics','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('about','Аб боце','Інфармацыя аб боце','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('profile','Профіль','Інфармацыя аб профілі','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeToday','Сёння','Сёння','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeYesterday','Учора','Учора','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('privateStatistics','privateStatistics','privateStatistics','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('publicStatistics','publicStatistics','publicStatistics','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterLocation','Патрабуецца фота ці відэа, апісанне і месцазнаходжанне.','Патрабуецца фота ці відэа, апісанне і месцазнаходжанне.','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterMedia','Отмена. Добавте фото или видео.','Отмена. Добавте фото или видео.','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterText','Отмена. Добавте текст.','Отмена. Добавте текст.','0');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('registration','Этот бот','Регистрация','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('language','Язык','Выберите удобный язык для Вас.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('languageSuccess','Вы выбрали русский язык.','Вы выбрали русский язык.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('main','Главная','В данном разделе представлены основной список возможностей бота, выберите нужный раздел нажатием на кнопку.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('back','Назад','Назад','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('setting','Настройки','Персональные настройки бота','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('help','Помощь','Помощь

Полная инструкция для бота - ','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('configuration','Конфигурация','Конфигурация','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('add','Добавить','Меню добавление происшествия.

Для добавление происшествия отправьте следующие запрашиваемые элементы.
- Местоположение ( справа в  нижнем углу в разделе добавления медиа файлов можно отправить геолокацию )
- Не менее одного медиафайла ( фото или видео )
- Любую письменную заметку о дтп ','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addLocation','Местоположение','Местоположение','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addPhotoCount','Количество фотографий','Количество фотографий : ','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addVideoCount','Количество видео','Количество видео : ','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirm','Подтвердить','Подтверждено.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameter','Требуется фото или видео, описание и местоположение.','Требуется медиа файл, описание и местоположение.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmBuild','Ваша заявка отправлена','Ваша заявка отправлена','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTime','Когда это произошло ?','Выберите время когда случилось данное происшествие','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTimeNow','Сейчас','Сейчас','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('addTimeSelect','Выбрать другое время','Выбрать другое время','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeDay','Выберите день месяца','Выберите день месяца','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeHour','Выберите час','Выберите час','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeMinute','Выберите точное время','Выберите точное время','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeMonth','Выберите месяц','Выберите месяц','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('january','Январь','Январь','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('february','Февраль','Февраль','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('march','Март','Март','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('april','Апрель','Апрель','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('may','Май','Май','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('june','Июнь','Июнь','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('july','Июль','Июль','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('august','Август','Август','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('september','Сентябрь','Сентябрь','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('october','Октябрь','Октябрь','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('november','Ноябрь','Ноябрь','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('december','Декабрь','Декабрь','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeYear','Выберите год','Выберите год','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('monday','Понедельник','Понедельник','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('tuesday','Вторник','Вторник','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('wednesday','Среда','Среда','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('thursday','Четверг','Четверг','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('friday','Пятница','Пятница','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('saturday','Суббота','Суббота','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('sunday','Воскресенье','Воскресенье','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('verifyBuild','Подтвердить','Подтвердить','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('rejectIncident','Отклоненные происшествия','Отклоненные происшествия','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queue','Очередь','Очередь','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queueBuildSize','Количество отправленных происшествий','Количество отправленных происшествий : ','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('queueRejectSize','Количество отклонённых происшествий','Количество отклонённых происшествий : ','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('editBuild','Редактировать','Редактировать','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('buildIncident','Отправленные происшествия','Отправленные происшествия','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('rejectBuild','Отклоненные происшествия','Отклоненные происшествия','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('deleteIncident','Удаленные происшествия','Удаленные происшествия','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('exception','Ошибка','Неактуальное действие или ошибка при обработке запроса. Попробуйте снова.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('statistics','Статистика','Статистика','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('about','О боте','Бот создан для упрощённого сбора всех дорожных аварий, произошедших на территории Республики Беларусь и последующего анализа с выявлением опасных мест.

Бот пригодится чиновникам, проектировщикам дорог и всем городским активистам, исследующим безопасность на дорогах. ','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('profile','Профиль','Персональные данные','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeToday','Сегодня','Сегодня','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('timeYesterday','Вчера','Вчера','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('privateStatistics','Приватная статистика','privateStatistics','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('publicStatistics','Публичная статистика','publicStatistics','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterLocation','Отмена. Добавте местоположение.','Отмена. Добавте местоположение.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterMedia','Отмена. Добавте фото или видео.','Отмена. Добавте фото или видео.','1');
INSERT INTO `beldtp`.`answer` (`type`,`label`,`text`,`language`) VALUES ('confirmRequiredParameterText','Отмена. Добавте текст.','Отмена. Добавте текст.','1');
